@ECHO OFF
SETLOCAL
SET "BATCH_SCRIPT_DIR=%~dp0"
SET "POWERSHELL_SCRIPT_NAME=Run-DailyNotes.ps1"
SET "POWERSHELL_SCRIPT_PATH=%BATCH_SCRIPT_DIR%%POWERSHELL_SCRIPT_NAME%"
powershell.exe -ExecutionPolicy Bypass -NoProfile -File "%POWERSHELL_SCRIPT_PATH%"
PAUSE
ENDLOCAL
